title: Front Commerce Developer Documentation
subtitle: Using Front Commerce
versions:
  - "1"
sidebar_categories:
  null:
    - docs/index
  Essentials:
    - docs/essentials/installation
    - docs/essentials/extend-the-theme
    - docs/essentials/adapt-theme-to-your-brand
    - docs/essentials/create-a-ui-component
    - docs/essentials/add-component-to-storybook
    - docs/essentials/create-a-business-component
    - docs/essentials/add-a-page-client-side
    - docs/essentials/extend-the-graphql-schema
  Theme:
    - docs/advanced/theme/overview
    - docs/advanced/theme/route-dispatcher
    - docs/advanced/theme/layouts
    - docs/advanced/theme/wysiwyg
    - docs/advanced/theme/wysiwyg-platform
    - docs/advanced/theme/form
    - docs/advanced/theme/analytics
    - docs/advanced/theme/translations
    - docs/advanced/theme/server-side-rendering
  GraphQL:
    - docs/advanced/graphql/overview
    - docs/advanced/graphql/meta-modules
    - docs/advanced/graphql/slim-down-resolvers-with-loaders
    - docs/advanced/graphql/dataloaders-and-cache-invalidation
    - docs/advanced/graphql/change-resolver-behavior
    - docs/advanced/graphql/remote-schemas
    - docs/advanced/graphql/rate-limiting
  Checkout:
    - docs/advanced/checkout/overview
    - docs/advanced/checkout/add-custom-checkout-step
  Server:
    - docs/advanced/server/overview
    - docs/advanced/server/add-http-endpoint
    - docs/advanced/server/customize-response-http-headers
    - docs/advanced/server/configurations
  Performance:
    - docs/advanced/performance/overview
    - docs/advanced/performance/preloading-routes
    - docs/advanced/performance/faster-server-side-rendering
    - docs/advanced/performance/server-timings
    - docs/advanced/performance/improve-your-core-web-vitals
    - docs/advanced/performance/cache-control-and-cdn
    - docs/advanced/performance/assets-cdn-domain
    - docs/advanced/performance/deactivating-unnecessary-features
  Production ready:
    - docs/advanced/production-ready/overview
    - docs/advanced/production-ready/media-middleware
    - docs/advanced/production-ready/multistore
    - docs/advanced/production-ready/logging
    - docs/advanced/production-ready/sessions
    - docs/advanced/production-ready/checklist-before-production
    - docs/advanced/production-ready/sitemap
    - docs/advanced/production-ready/front-commerce-and-pm2
  Features:
    - docs/advanced/features/overview
    - docs/advanced/features/invoices
    - docs/advanced/features/flash-messages
    - docs/advanced/features/display-a-map
    - docs/advanced/features/smart-forms
    - docs/advanced/features/quickorder
    - docs/advanced/features/external-logins
    - docs/advanced/features/return-merchandise-authorization
    - docs/advanced/features/in-stock-alert
  Concepts:
    - docs/concepts/architecture-overview
    - docs/concepts/front-commerce-folder-structure
    - docs/concepts/react-components-structure
  Magento2:
    - docs/magento2/overview
    - docs/magento2/graphql
    - docs/magento2/search-engine
    - docs/magento2/i18n
    - docs/magento2/add-new-attribute
    - docs/magento2/using-magento-configuration
    - docs/magento2/detect-admin-users
    - docs/magento2/log-as-customer
    - docs/magento2/headless-payments
    - docs/magento2/page-builder
    - docs/magento2/commerce
    - docs/magento2/b2b
    - docs/magento2/advanced
  Magento1:
    - docs/magento1/overview
    - docs/magento1/installation
    - docs/magento1/search-engine
    - docs/magento1/add-custom-endpoint
    - docs/magento1/exposing-additional-attributes
    - docs/magento1/event-list
    - docs/magento1/generate-api-doc
    - docs/magento1/headless-payments
    - docs/magento1/advanced
  Prismic:
    - docs/prismic/index
    - docs/prismic/installation
    - docs/prismic/expose-content
    - docs/prismic/content-slices
    - docs/prismic/routable-types
    - docs/prismic/integration-fields
    - docs/prismic/preview
    - docs/prismic/embed-fields
  Payments:
    - docs/advanced/payments/overview
    - docs/advanced/payments/payment-workflows
    - docs/advanced/payments/front-commerce-payments
    - docs/advanced/payments/adyen
    - docs/advanced/payments/affirm
    - docs/advanced/payments/buybox
    - docs/advanced/payments/hipay
    - docs/advanced/payments/ingenico
    - docs/advanced/payments/payline
    - docs/advanced/payments/paypal
    - docs/advanced/payments/payzen
    - docs/advanced/payments/stripe
    - docs/advanced/payments/payment-on-account
    - docs/advanced/payments/custom-payment-information
  Shipping:
    - docs/advanced/shipping/overview
    - docs/advanced/shipping/custom-shipping-information
    - docs/advanced/shipping/add-new-shipping-data-in-graphql
    - docs/advanced/shipping/colissimo
    - docs/advanced/shipping/mondial-relay
  Reference:
    - docs/reference/front-commerce-js
    - docs/reference/configurations
    - docs/reference/environment-variables
    - docs/reference/debugging
    - docs/reference/cli
    - docs/reference/graphql-module-definition
    - docs/reference/remote-schema-helpers
    - docs/reference/graphql-context
    - docs/reference/routing
    - docs/reference/analytics-components
    - docs/reference/scripts
    - docs/reference/front-commerce-prepare
    - docs/reference/use-selected-product-with-configurable-options
  Appendices:
    - docs/appendices/troubleshooting
    - docs/appendices/release-process
    - docs/appendices/migration-guides
    - docs/appendices/release-notes
    - docs/appendices/changelog

github_repo: front-commerce/developers.front-commerce.com

nav_links:
  "Home":
    url: /
  "Docs":
    url: /docs/
  "Changelog":
    url: /blog/
  'Support <span class="icon-request-change"></span>':
    url: https://help.front-commerce.com/en/articles/5910607-when-how-can-i-reach-the-front-commerce-support-team

community_links:
  "Slack":
    url: "https://join.slack.com/t/front-commerce/shared_invite/enQtMzI2OTEyMDYzOTkxLWEzODg2NjM5MmVhNGUwODE0OTI4MWMwYTcxZWZkNzE1YjU4MzRlZmQ0YWY5NDNkZWM0ZGMzMGQ4NDc4OTgxMTU"
  "Twitter":
    url: "https://twitter.com/Front_Commerce"
  "Contact":
    url: "https://www.front-commerce.com/en/contact-us/"

url: https://developers.front-commerce.com/
root: /
permalink: blog/:year/:month/:day/:title/

public_dir: public/

sitemap:
  path: sitemap.xml
  rel: true
