title: Front Commerce Developer Documentation
subtitle: Using Front Commerce
versions:
  - "1"
sidebar_categories:
  null:
    - docs/index
  Essentials:
    - docs/essentials/installation
    - docs/essentials/extend-the-theme
    - docs/essentials/adapt-theme-to-your-brand
    - docs/essentials/create-a-ui-component
    - docs/essentials/add-component-to-storybook
    - docs/essentials/create-a-business-component
    - docs/essentials/add-a-page-client-side
    - docs/essentials/extend-the-graphql-schema
  Theme:
    - docs/advanced/theme/overview
    - docs/advanced/theme/route-dispatcher
    - docs/advanced/theme/layouts
    - docs/advanced/theme/wysiwyg
    - docs/advanced/theme/wysiwyg-platform
    - docs/advanced/theme/form
    - docs/advanced/theme/analytics
    - docs/advanced/theme/translations
    - docs/advanced/theme/server-side-rendering
  GraphQL:
    - docs/advanced/graphql/overview
    - docs/advanced/graphql/meta-modules
    - docs/advanced/graphql/slim-down-resolvers-with-loaders
    - docs/advanced/graphql/dataloaders-and-cache-invalidation
    - docs/advanced/graphql/remote-schemas
    - docs/advanced/graphql/rate-limiting
  Checkout:
    - docs/advanced/checkout/overview
    - docs/advanced/checkout/add-custom-checkout-step
  Server:
    - docs/advanced/server/overview
    - docs/advanced/server/add-http-endpoint
    - docs/advanced/server/configurations
  Performance:
    - docs/advanced/performance/overview
    - docs/advanced/performance/preloading-routes
    - docs/advanced/performance/faster-server-side-rendering
    - docs/advanced/performance/server-timings
  Production ready:
    - docs/advanced/production-ready/overview
    - docs/advanced/production-ready/media-middleware
    - docs/advanced/production-ready/multistore
    - docs/advanced/production-ready/logging
    - docs/advanced/production-ready/checklist-before-production
    - docs/advanced/production-ready/sitemap
  Payments:
    - docs/advanced/payments/overview
    - docs/advanced/payments/payment-workflows
    - docs/advanced/payments/front-commerce-payments
    - docs/advanced/payments/magento2-headless-payments
    - docs/advanced/payments/stripe
    - docs/advanced/payments/paypal
    - docs/advanced/payments/payzen
    - docs/advanced/payments/ingenico
  Concepts:
    - docs/concepts/architecture-overview
    - docs/concepts/front-commerce-folder-structure
    - docs/concepts/react-components-structure
  Magento2:
    - docs/magento2/overview
    - docs/magento2/graphql
    - docs/magento2/i18n
    - docs/magento2/add-new-attribute
    - docs/magento2/using-magento-configuration
    - docs/magento2/detect-admin-users
  Magento1:
    - docs/magento1/overview
    - docs/magento1/installation
    - docs/magento1/add-custom-endpoint
    - docs/magento1/event-list
    - docs/magento1/generate-api-doc
  Reference:
    - docs/reference/front-commerce-js
    - docs/reference/configurations
    - docs/reference/environment-variables
    - docs/reference/cli
    - docs/reference/graphql-module-definition
    - docs/reference/graphql-context
    - docs/reference/api
    - docs/reference/routing
    - docs/reference/analytics-components
    - docs/reference/scripts
    - docs/reference/front-commerce-prepare
  Appendices:
    - docs/appendices/troubleshooting
    - docs/appendices/release-process
    - docs/appendices/migration-guides
    - docs/appendices/release-notes
    - docs/appendices/changelog

github_repo: front-commerce/developers.front-commerce.com

nav_links:
  "Home":
    url: /
  "Docs":
    url: /docs/
  "Help":
    url: /help.html
  "License":
    url: /license.html
  "Blog":
    url: /blog/

community_links:
  "Slack":
    url: "https://join.slack.com/t/front-commerce/shared_invite/enQtMzI2OTEyMDYzOTkxLWEzODg2NjM5MmVhNGUwODE0OTI4MWMwYTcxZWZkNzE1YjU4MzRlZmQ0YWY5NDNkZWM0ZGMzMGQ4NDc4OTgxMTU"
  "Twitter":
    url: "https://twitter.com/Front_Commerce"
  "Contact":
    url: "mailto:contact@front-commerce.com"

url: https://developers.front-commerce.com/
root: /
permalink: blog/:year/:month/:day/:title/

public_dir: public/

sitemap:
  path: sitemap.xml
  rel: true
